site_name: Pixano Documentation
theme:
  name: material
  logo: assets/pixano_white.png
  favicon: assets/pixano.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Poppins
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.integrate
repo_url: https://github.com/pixano/pixano
repo_name: pixano/pixano
copyright: Licensed under the CeCILL-C license
extra:
  social:
    - icon: material/email-outline
      link: mailto:pixano@cea.fr
      name: Contact us
    - icon: material/web
      link: https://list.cea.fr/en/
      name: CEA LIST
    - icon: fontawesome/brands/github
      link: https://github.com/pixano/pixano
      name: Pixano on GitHub
extra_css:
  - assets/extra.css
plugins:
  - search
  - autorefs

nav:
  - "Home": index.md
  - "Pixano": https://pixano.github.io/pixano/
  - "Pixano Inference": https://pixano.github.io/pixano-inference/
